const state = {
  recipes: [
    {
        title: 'Endeusiast Udah Tau Jenis tempe Ini belum?',
        imgSrc: 'https://img.kurio.network/JFv-HwLimSuUmzpyvgp-wY9KpPk=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/23/07/03/6f389227-27f0-4363-ad1a-9493ebf5a840.jpg',
        hasVideo: true,
        duration: 10,
        id: 1,
        category: 'resep-tempe',
        videoUrl: 'https://video-files.kurio.co.id/23/07/03/5d701f1c-298e-4c85-8014-89eed30be29c.sd.mp4',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari <cam></cam>puran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Nasi Goreng Sambal Pete',
        imgSrc: 'https://img.kurio.network/BCjOpzXk9v-v1TgzmLGHiRHL93M=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/23/03/27/1e4bcd20-fe42-4dbc-a9b3-6846da688644.png',
        hasVideo: true,
        duration: 20,
        id: 2,
        category: 'resep-tempe',
        videoUrl: 'https://video-files.kurio.co.id/23/03/30/1f7bf99b-76b8-487a-b0cf-42d51861a23f.sd.mp4',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 4,
        stars: 4.8,
        total_review: 4,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Sambal Tempe Kentang',
        imgSrc: 'https://img.kurio.network/syP1Lo__aJ1xIZqX-I3GxL9j04k=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/23/03/27/6464708a-d0ff-44a0-9152-59a095d916b7.png',
        hasVideo: false,
        duration: 30,
        id: 3,
        category: 'resep-tempe',
        videoUrl: '',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 3,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Shihlin Tempe Ala Royco',
        imgSrc: 'https://img.kurio.network/m7nDFUUzevI1nGxnu3qfM7MBFag=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/22/10/21/bb31b80d-3054-4b66-82e1-550a0db2705e.jpg',
        hasVideo: true,
        duration: 30,
        id: 4,
        category: 'resep-tempe',
        videoUrl: '',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 3.2,
        total_review: 9,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Resep Perkedel Tempe Telur, Lauk Simpel dan Enak',
        imgSrc: 'https://img.kurio.network/_q010Bsa4wNStQL2iJ6IgNHOa44=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/22/09/26/c14d1382-2e9f-4d54-ad6e-c3f5d0a7edca.jpg',
        hasVideo: false,
        duration: 35,
        id: 5,
        category: 'resep-tempe',
        videoUrl: '',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Steak Tempe Saus Lada Hitam yang Ngga Kalah Enak Dari Steak Daging',
        imgSrc: 'https://img.kurio.network/yGDU2736iTHAKo_o-prPkpNSy3U=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/22/09/13/a5ba5a1f-5df8-45da-abdf-55f0fdadb4a4.jpg',
        hasVideo: false,
        duration: 40,
        id: 6,
        category: 'resep-tempe',
        videoUrl: '',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Resep Sayur Lodeh Betawi, Lauk Berkuah yang Menggugah Selera',
        imgSrc: 'https://img.kurio.network/aV0DkxtKlmd8O361a57fuBaPO_Q=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/22/08/02/8ecac948-dc06-4f96-a04a-0810afbb6acc.jpg',
        hasVideo: false,
        duration: 10,
        id: 7,
        category: 'resep-tempe',
        videoUrl: '',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 4.5,
        total_review: 5,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Botok Teri',
        imgSrc: 'https://img.kurio.network/fP9m81di8LSiddqgE0VYd4-l72A=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/22/07/29/3febf28d-4da7-42b6-86b3-1f62c215e553.jpg',
        hasVideo: false,
        duration: 10,
        id: 8,
        category: 'resep-tempe',
        videoUrl: '',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Tempe Goreng Ketumbar',
        imgSrc: 'https://img.kurio.network/5R3PuONejg5I9V7wrKtltSLLDX0=/380x380/filters:quality(80):watermark(https://kurio-img.kurioapps.com/21/04/15/df401e7c-7b29-428a-9a16-aad1fafe07a1.png,0,5p,0,24)/https://kurio-img.kurioapps.com/22/07/26/c1eb4ab7-ba7d-4915-a6c0-8c2180e3c98f.jpg',
        hasVideo: false,
        duration: 10,
        id: 9,
        category: 'resep-tempe',
        videoUrl: '',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Tumis Genjer Tempe, Menu Praktis yang Menggugah Selera',
        imgSrc: 'https://img.kurio.network/yH1wqkdeuQPIn6G4SdVorBRKUNI=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/22/07/22/7dd6bd27-41dd-4e0e-a049-efae041551e5.jpg',
        hasVideo: false,
        duration: 30,
        id: 10,
        category: 'resep-tempe',
        videoUrl: '',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Soto Kerbau Asal Kudus, Satu Mangkok Nggak Cukup',
        imgSrc: 'https://img.kurio.network/cqkcXVdipKHd2jKWbbNwH75VWxM=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/22/07/11/aacba051-7404-4ccd-a3c4-31c8986b7d84.jpg',
        hasVideo: false,
        duration: 90,
        id: 11,
        category: 'resep-tempe',
        videoUrl: '',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Rujak Soto Khas Banyuwangi, Rasanya Bikin Ketagihan',
        imgSrc: 'https://img.kurio.network/g02ZtsFclA5pli6877BfvgAbVPA=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/22/06/29/56de2936-7b26-441a-896e-1adb9cb8d35c.jpe',
        hasVideo: false,
        duration: 60,
        id: 12,
        category: 'resep-tempe',
        videoUrl: '',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Cara Menyusun Tumpeng',
        imgSrc: 'https://img.kurio.network/BDS-vVPXynkgKx_93jJq7x6Xxhk=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/22/07/28/cb311c7b-8f48-4524-9fb1-54b55b70a1cd.jpg',
        hasVideo: true,
        duration: 50,
        id: 13,
        category: 'resep-tempe',
        videoUrl: 'https://video-files.kurio.co.id/22/07/29/95cf5099-8fe3-4b37-871f-5cf502c3b680.sd.mp4',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },

    
    {
        title: 'Tempe Goreng Ketumbar',
        imgSrc: 'https://img.kurio.network/5R3PuONejg5I9V7wrKtltSLLDX0=/380x380/filters:quality(80):watermark(https://kurio-img.kurioapps.com/21/04/15/df401e7c-7b29-428a-9a16-aad1fafe07a1.png,0,5p,0,24)/https://kurio-img.kurioapps.com/22/07/26/c1eb4ab7-ba7d-4915-a6c0-8c2180e3c98f.jpg',
        hasVideo: false,
        duration: 10,
        id: 24,
        category: 'resep-tempe',
        videoUrl: '',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Tumis Genjer Tempe, Menu Praktis yang Menggugah Selera',
        imgSrc: 'https://img.kurio.network/yH1wqkdeuQPIn6G4SdVorBRKUNI=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/22/07/22/7dd6bd27-41dd-4e0e-a049-efae041551e5.jpg',
        hasVideo: false,
        duration: 30,
        id: 23,
        category: 'resep-ayam',
        videoUrl: '',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Soto Kerbau Asal Kudus, Satu Mangkok Nggak Cukup',
        imgSrc: 'https://img.kurio.network/cqkcXVdipKHd2jKWbbNwH75VWxM=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/22/07/11/aacba051-7404-4ccd-a3c4-31c8986b7d84.jpg',
        hasVideo: false,
        duration: 90,
        id: 22,
        category: 'resep-ayam',
        videoUrl: '',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Rujak Soto Khas Banyuwangi, Rasanya Bikin Ketagihan',
        imgSrc: 'https://img.kurio.network/g02ZtsFclA5pli6877BfvgAbVPA=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/22/06/29/56de2936-7b26-441a-896e-1adb9cb8d35c.jpe',
        hasVideo: false,
        duration: 60,
        id: 21,
        category: 'resep-ayam',
        videoUrl: '',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Cara Menyusun Tumpeng',
        imgSrc: 'https://img.kurio.network/BDS-vVPXynkgKx_93jJq7x6Xxhk=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/22/07/28/cb311c7b-8f48-4524-9fb1-54b55b70a1cd.jpg',
        hasVideo: true,
        duration: 50,
        id: 20,
        category: 'resep-tempe',
        videoUrl: 'https://video-files.kurio.co.id/22/07/29/95cf5099-8fe3-4b37-871f-5cf502c3b680.sd.mp4',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Botok Teri',
        imgSrc: 'https://img.kurio.network/fP9m81di8LSiddqgE0VYd4-l72A=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/22/07/29/3febf28d-4da7-42b6-86b3-1f62c215e553.jpg',
        hasVideo: false,
        duration: 10,
        id: 30,
        category: 'resep-tahu',
        videoUrl: '',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Tempe Goreng Ketumbar',
        imgSrc: 'https://img.kurio.network/5R3PuONejg5I9V7wrKtltSLLDX0=/380x380/filters:quality(80):watermark(https://kurio-img.kurioapps.com/21/04/15/df401e7c-7b29-428a-9a16-aad1fafe07a1.png,0,5p,0,24)/https://kurio-img.kurioapps.com/22/07/26/c1eb4ab7-ba7d-4915-a6c0-8c2180e3c98f.jpg',
        hasVideo: false,
        duration: 10,
        id: 31,
        category: 'resep-ikan',
        videoUrl: '',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Tumis Genjer Tempe, Menu Praktis yang Menggugah Selera',
        imgSrc: 'https://img.kurio.network/yH1wqkdeuQPIn6G4SdVorBRKUNI=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/22/07/22/7dd6bd27-41dd-4e0e-a049-efae041551e5.jpg',
        hasVideo: false,
        duration: 30,
        id: 32,
        category: 'resep-ikan',
        videoUrl: '',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Soto Kerbau Asal Kudus, Satu Mangkok Nggak Cukup',
        imgSrc: 'https://img.kurio.network/cqkcXVdipKHd2jKWbbNwH75VWxM=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/22/07/11/aacba051-7404-4ccd-a3c4-31c8986b7d84.jpg',
        hasVideo: false,
        duration: 90,
        id: 33,
        category: 'resep-tahu',
        videoUrl: '',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Rujak Soto Khas Banyuwangi, Rasanya Bikin Ketagihan',
        imgSrc: 'https://img.kurio.network/g02ZtsFclA5pli6877BfvgAbVPA=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/22/06/29/56de2936-7b26-441a-896e-1adb9cb8d35c.jpe',
        hasVideo: false,
        duration: 60,
        id: 34,
        category: 'resep-tempe',
        videoUrl: '',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Cara Menyusun Tumpeng',
        imgSrc: 'https://img.kurio.network/BDS-vVPXynkgKx_93jJq7x6Xxhk=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/22/07/28/cb311c7b-8f48-4524-9fb1-54b55b70a1cd.jpg',
        hasVideo: true,
        duration: 50,
        id: 35,
        category: 'resep-tempe',
        videoUrl: 'https://video-files.kurio.co.id/22/07/29/95cf5099-8fe3-4b37-871f-5cf502c3b680.sd.mp4',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },

    
    {
        title: 'Tempe Goreng Ketumbar',
        imgSrc: 'https://img.kurio.network/5R3PuONejg5I9V7wrKtltSLLDX0=/380x380/filters:quality(80):watermark(https://kurio-img.kurioapps.com/21/04/15/df401e7c-7b29-428a-9a16-aad1fafe07a1.png,0,5p,0,24)/https://kurio-img.kurioapps.com/22/07/26/c1eb4ab7-ba7d-4915-a6c0-8c2180e3c98f.jpg',
        hasVideo: false,
        duration: 10,
        id: 36,
        category: 'resep-tempe',
        videoUrl: '',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Tumis Genjer Tempe, Menu Praktis yang Menggugah Selera',
        imgSrc: 'https://img.kurio.network/yH1wqkdeuQPIn6G4SdVorBRKUNI=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/22/07/22/7dd6bd27-41dd-4e0e-a049-efae041551e5.jpg',
        hasVideo: false,
        duration: 30,
        id: 37,
        category: 'resep-ayam',
        videoUrl: '',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },




    {
        title: 'Tempe Goreng Ketumbar',
        imgSrc: 'https://img.kurio.network/5R3PuONejg5I9V7wrKtltSLLDX0=/380x380/filters:quality(80):watermark(https://kurio-img.kurioapps.com/21/04/15/df401e7c-7b29-428a-9a16-aad1fafe07a1.png,0,5p,0,24)/https://kurio-img.kurioapps.com/22/07/26/c1eb4ab7-ba7d-4915-a6c0-8c2180e3c98f.jpg',
        hasVideo: false,
        duration: 10,
        id: 40,
        category: 'aneka-nasi',
        videoUrl: '',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Tumis Genjer Tempe, Menu Praktis yang Menggugah Selera',
        imgSrc: 'https://img.kurio.network/yH1wqkdeuQPIn6G4SdVorBRKUNI=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/22/07/22/7dd6bd27-41dd-4e0e-a049-efae041551e5.jpg',
        hasVideo: false,
        duration: 30,
        id: 41,
        category: 'resep-ayam',
        videoUrl: '',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Soto Kerbau Asal Kudus, Satu Mangkok Nggak Cukup',
        imgSrc: 'https://img.kurio.network/cqkcXVdipKHd2jKWbbNwH75VWxM=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/22/07/11/aacba051-7404-4ccd-a3c4-31c8986b7d84.jpg',
        hasVideo: false,
        duration: 90,
        id: 42,
        category: 'resep-ayam',
        videoUrl: '',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Rujak Soto Khas Banyuwangi, Rasanya Bikin Ketagihan',
        imgSrc: 'https://img.kurio.network/g02ZtsFclA5pli6877BfvgAbVPA=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/22/06/29/56de2936-7b26-441a-896e-1adb9cb8d35c.jpe',
        hasVideo: false,
        duration: 60,
        id: 43,
        category: 'mpasi',
        videoUrl: '',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Cara Menyusun Tumpeng',
        imgSrc: 'https://img.kurio.network/BDS-vVPXynkgKx_93jJq7x6Xxhk=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/22/07/28/cb311c7b-8f48-4524-9fb1-54b55b70a1cd.jpg',
        hasVideo: true,
        duration: 50,
        id: 44,
        category: 'aneka-nasi',
        videoUrl: 'https://video-files.kurio.co.id/22/07/29/95cf5099-8fe3-4b37-871f-5cf502c3b680.sd.mp4',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Botok Teri',
        imgSrc: 'https://img.kurio.network/fP9m81di8LSiddqgE0VYd4-l72A=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/22/07/29/3febf28d-4da7-42b6-86b3-1f62c215e553.jpg',
        hasVideo: false,
        duration: 10,
        id: 45,
        category: 'mpasi',
        videoUrl: '',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },

    {
        title: 'Soto Kerbau Asal Kudus, Satu Mangkok Nggak Cukup',
        imgSrc: 'https://img.kurio.network/cqkcXVdipKHd2jKWbbNwH75VWxM=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/22/07/11/aacba051-7404-4ccd-a3c4-31c8986b7d84.jpg',
        hasVideo: false,
        duration: 90,
        id: 80,
        category: '<resep-roti></resep-roti>',
        videoUrl: '',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Rujak Soto Khas Banyuwangi, Rasanya Bikin Ketagihan',
        imgSrc: 'https://img.kurio.network/g02ZtsFclA5pli6877BfvgAbVPA=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/22/06/29/56de2936-7b26-441a-896e-1adb9cb8d35c.jpe',
        hasVideo: false,
        duration: 60,
        id: 81,
        category: 'resep-roti',
        videoUrl: '',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Cara Menyusun Tumpeng',
        imgSrc: 'https://img.kurio.network/BDS-vVPXynkgKx_93jJq7x6Xxhk=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/22/07/28/cb311c7b-8f48-4524-9fb1-54b55b70a1cd.jpg',
        hasVideo: true,
        duration: 50,
        id: 82,
        category: 'aneka-nasi',
        videoUrl: 'https://video-files.kurio.co.id/22/07/29/95cf5099-8fe3-4b37-871f-5cf502c3b680.sd.mp4',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Botok Teri',
        imgSrc: 'https://img.kurio.network/fP9m81di8LSiddqgE0VYd4-l72A=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/22/07/29/3febf28d-4da7-42b6-86b3-1f62c215e553.jpg',
        hasVideo: false,
        duration: 10,
        id: 83,
        category: 'resep-roti',
        videoUrl: '',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },



    {
        title: 'Rujak Soto Khas Banyuwangi, Rasanya Bikin Ketagihan',
        imgSrc: 'https://img.kurio.network/g02ZtsFclA5pli6877BfvgAbVPA=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/22/06/29/56de2936-7b26-441a-896e-1adb9cb8d35c.jpe',
        hasVideo: false,
        duration: 60,
        id: 100,
        category: 'cukup-5-bahan',
        videoUrl: '',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Cara Menyusun Tumpeng',
        imgSrc: 'https://img.kurio.network/BDS-vVPXynkgKx_93jJq7x6Xxhk=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/22/07/28/cb311c7b-8f48-4524-9fb1-54b55b70a1cd.jpg',
        hasVideo: true,
        duration: 50,
        id: 101,
        category: 'cukup-5-bahan',
        videoUrl: 'https://video-files.kurio.co.id/22/07/29/95cf5099-8fe3-4b37-871f-5cf502c3b680.sd.mp4',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Botok Teri',
        imgSrc: 'https://img.kurio.network/fP9m81di8LSiddqgE0VYd4-l72A=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/22/07/29/3febf28d-4da7-42b6-86b3-1f62c215e553.jpg',
        hasVideo: false,
        duration: 10,
        id: 103,
        category: 'cukup-5-bahan',
        videoUrl: '',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },


    {
        title: 'Endeusiast Udah Tau Jenis tempe Ini belum?',
        imgSrc: 'https://img.kurio.network/JFv-HwLimSuUmzpyvgp-wY9KpPk=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/23/07/03/6f389227-27f0-4363-ad1a-9493ebf5a840.jpg',
        hasVideo: true,
        duration: 10,
        id: 201,
        category: 'resep-sehat',
        videoUrl: 'https://video-files.kurio.co.id/23/07/03/5d701f1c-298e-4c85-8014-89eed30be29c.sd.mp4',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari <cam></cam>puran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Nasi Goreng Sambal Pete',
        imgSrc: 'https://img.kurio.network/BCjOpzXk9v-v1TgzmLGHiRHL93M=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/23/03/27/1e4bcd20-fe42-4dbc-a9b3-6846da688644.png',
        hasVideo: true,
        duration: 20,
        id: 202,
        category: 'resep-sehat',
        videoUrl: 'https://video-files.kurio.co.id/23/03/30/1f7bf99b-76b8-487a-b0cf-42d51861a23f.sd.mp4',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 4,
        stars: 4.8,
        total_review: 4,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Sambal Tempe Kentang',
        imgSrc: 'https://img.kurio.network/syP1Lo__aJ1xIZqX-I3GxL9j04k=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/23/03/27/6464708a-d0ff-44a0-9152-59a095d916b7.png',
        hasVideo: false,
        duration: 30,
        id: 203,
        category: 'resep-sehat',
        videoUrl: '',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 3,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Shihlin Tempe Ala Royco',
        imgSrc: 'https://img.kurio.network/m7nDFUUzevI1nGxnu3qfM7MBFag=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/22/10/21/bb31b80d-3054-4b66-82e1-550a0db2705e.jpg',
        hasVideo: true,
        duration: 30,
        id: 204,
        category: 'resep-sehat',
        videoUrl: '',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 3.2,
        total_review: 9,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Resep Perkedel Tempe Telur, Lauk Simpel dan Enak',
        imgSrc: 'https://img.kurio.network/_q010Bsa4wNStQL2iJ6IgNHOa44=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/22/09/26/c14d1382-2e9f-4d54-ad6e-c3f5d0a7edca.jpg',
        hasVideo: false,
        duration: 35,
        id: 205,
        category: 'resep-sehat',
        videoUrl: '',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
   
    


    {
        title: 'Sambal Tempe Kentang',
        imgSrc: 'https://img.kurio.network/syP1Lo__aJ1xIZqX-I3GxL9j04k=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/23/03/27/6464708a-d0ff-44a0-9152-59a095d916b7.png',
        hasVideo: false,
        duration: 30,
        id: 303,
        category: 'aneka-minuman',
        videoUrl: '',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 3,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Shihlin Tempe Ala Royco',
        imgSrc: 'https://img.kurio.network/m7nDFUUzevI1nGxnu3qfM7MBFag=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/22/10/21/bb31b80d-3054-4b66-82e1-550a0db2705e.jpg',
        hasVideo: true,
        duration: 30,
        id: 304,
        category: 'aneka-minuman',
        videoUrl: '',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 3.2,
        total_review: 9,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
    {
        title: 'Resep Perkedel Tempe Telur, Lauk Simpel dan Enak',
        imgSrc: 'https://img.kurio.network/_q010Bsa4wNStQL2iJ6IgNHOa44=/380x380/filters:quality(80)/https://kurio-img.kurioapps.com/22/09/26/c14d1382-2e9f-4d54-ad6e-c3f5d0a7edca.jpg',
        hasVideo: false,
        duration: 35,
        id: 305,
        category: 'aneka-minuman',
        videoUrl: '',
        seasoning: [  "8 buah cabai merah besar",  "10 butir bawang merah",  "5 siung bawang putih",  "2 sdt gula merah, sisir halus"],
        bahan: [  "minyak goreng",  "200 g kentang, kupas, potong dadu 1 cm",  "300 g tempe, potong dadu 1 cm",  "6 lembar daun jeruk",  "2 lembar daun salam",  "2 cm lengkuas, memarkan",  "2 batang serai, memarkan",  "10 buah mata petai, belah dua",  "1 sdt kaldu sapi bubuk",  "1 sdm air asam jawa pekat",  "150 ml air",  "1 sdm bawang merah goreng"],
        tutorial: [  "Panaskan minyak goreng banyak dalam wajan, goreng kentang, dan tempe secara terpisah hingga matang",  "Angkat, tiriskan",  "Sisihkan",  "Panaskan 4 sdm minyak sisa menggoreng bahan, tumis bumbu halus, daun jeruk, daun salam, lengkuas, dan serai hingga harum",  "Masukkan petai, kentang, tempe, kaldu sapi bubuk, air asam jawa, dan air, aduk hingga rata",  "Masak hingga cairan menyusut",  "Angkat, sajikan segera dengan taburan bawang merah goreng"],
        porsi: 6,
        stars: 5,
        total_review: 3,
        desc: 'Sambal goreng dari campuran tempe, kentang, dan pete. Tidak pedas dan cocok untuk menu berbuka dan sahur yang tahan lama.'
    },
  ]
}

const getters = {
  getFilteredRecipes: state => param => {
    return state.recipes.filter(recipe => recipe.category === param)
  },
  getRecipeById: state => id => {
    console.log(id, state.recipes.find(recipe => recipe.id === id))
    return state.recipes.find(recipe => recipe.id === id)
  }
}

const actions = {
}


export default {
    namespaced: true,
    state,
    getters,
    actions
}